version: "3.9"
services:
  pg_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    ports:
      - '5432:5432'

  app:
    build:
      context: .
    command: npm run dev
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: pg_db
      DB_NAME: dev_db
      DB_SSL: false
    depends_on:
      - pg_db
    ports:
      - '3000:3000'
    volumes:
      - ./src/:/usr/app/src/
      - ./package.json:/usr/app/package.json
